# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mrdialog 1.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "mrdialog"
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Aleks Clark", "Muhammad Muquit"]
  s.date = "2018-04-12"
  s.description = "A ruby gem for ncurses dialog program.\n      This gem is based on rdialog (http://rdialog.rubyforge.org/) by\n      Aleks Clark. I added support for missing widgets, fixed \n      bugs and wrote the sample apps. I am \n      also renaming the class to MRDialog to avoid conflicts.\n      Please look at ChangeLog.md for details.  "
  s.email = "muquit@gmail.com"
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "ChangeLog.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/mrdialog.rb",
    "lib/mrdialog/mrdialog.rb",
    "pkg/md5.txt",
    "pkg/mrdialog-1.0.3.gem",
    "samples/buildlist.rb",
    "samples/calendar.rb",
    "samples/checklist.rb",
    "samples/editbox.rb",
    "samples/form1.rb",
    "samples/form2.rb",
    "samples/form3.rb",
    "samples/fselect.rb",
    "samples/gauge.rb",
    "samples/infobox.rb",
    "samples/inputbox.rb",
    "samples/menubox.rb",
    "samples/mixedform1.rb",
    "samples/msgbox.rb",
    "samples/password.rb",
    "samples/password2.rb",
    "samples/passwordform.rb",
    "samples/pause.rb",
    "samples/prgbox.rb",
    "samples/program.rb",
    "samples/progress.rb",
    "samples/radiolist.rb",
    "samples/run_all.rb",
    "samples/shortlist",
    "samples/timebox.rb",
    "samples/treeview.rb",
    "samples/treeview2.rb",
    "samples/yesno.rb",
    "screenshots/README.txt",
    "screenshots/all.gif",
    "screenshots/buildlist.png",
    "screenshots/calendar.png",
    "screenshots/checklist.png",
    "screenshots/editbox.png",
    "screenshots/form1.png",
    "screenshots/form2.png",
    "screenshots/form3.png",
    "screenshots/fselect.png",
    "screenshots/gauge.png",
    "screenshots/infobox.png",
    "screenshots/inputbox.png",
    "screenshots/menubox.png",
    "screenshots/mixedform1.png",
    "screenshots/msgbox.png",
    "screenshots/password.png",
    "screenshots/password2.png",
    "screenshots/passwordform.png",
    "screenshots/pause.png",
    "screenshots/prgbox.png",
    "screenshots/program.png",
    "screenshots/progress.png",
    "screenshots/radiolist.png",
    "screenshots/take_shots.rb",
    "screenshots/timebox.png",
    "screenshots/treeview.png",
    "screenshots/treeview2.png",
    "screenshots/yesno.png",
    "test/helper.rb",
    "test/test_mrdialog.rb"
  ]
  s.homepage = "http://github.com/muquit/mrdialog"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.2.1"
  s.summary = "A ruby gem for ncurses dialog program, based on the gem rdialog"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<juwelier>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<juwelier>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

